name: app_updater_repository
description: A Dart Repository which the process cleanup domain.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  path: ^1.8.0
  file: ^6.1.2
  intl: ^0.17.0
  dio: ^4.0.4
  version: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0
  test_utilities:
    path: ../test_utilities
